### ISSUE TITLE
missing notification when the setMaxFileSize value exceeded?

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-upload-flow#107]
_From @poczenorbert on December 19, 2018 8:44_

### Description
When selected a file to upload with a size greater than set by setMaxFileSize nothing happens

### Expected outcome
Notification shown and/or a FailedEvent or FileRejectEvent generated

### Actual outcome
Nothing happens.

### Steps to reproduce
https://vaadin.com/start/latest/project-base
Vaadin Flow version 12.0.3 with productionMode=true
upload.setMaxFileSize(1);

### Browsers Affected

- [x ] Chrome
- [x ] Firefox
- [ x] IE 11
- [x ] iOS Safari

_Copied from original issue: vaadin/vaadin-upload#296_

**Comment by web-padawan** [comment]
_From @poczenorbert on December 19, 2018 11:10_

I have this issue just when the setMaxFileSize( ) is used and a file with greater size is selected for upload.
To reproduce start with vaadin starter project base and change the MainView class like this:

`public MainView() {
        Button button = new Button("Click me",
                event -> Notification.show("Clicked!"));
        MemoryBuffer buffer = new MemoryBuffer();
        Upload upload = new Upload(buffer);
        upload.setUploadButton(button);
        upload.setMaxFileSize(1);
        upload.addFailedListener(failedEvent -> {
            Notification notification = Notification.show("Upload failed.");
        });
        upload.addSucceededListener(uploadEvent -> {
            Notification notification = Notification.show("Upload ok. fileName="+uploadEvent.getFileName());
        });
        add(upload);
    }`

**Comment by PavloRybakov** [comment]
there is a ClassCastException in the JsonCodec.class, see line 225 with _return type.cast(json);_, 
when JreJsonString with the error-Text **"file is too big"** has to be convert to a JsonObject:

java.lang.ClassCastException: Cannot cast elemental.json.impl.JreJsonString to elemental.json.JsonObject
	at java.lang.Class.cast(Class.java:3369)
	at com.vaadin.flow.internal.JsonCodec.decodeAs(JsonCodec.java:225)
	at com.vaadin.flow.component.ComponentEventBus.lambda$createEventDataObjects$2(ComponentEventBus.java:314)

**Comment by KasparScherrer** [comment]
This also applies to `maxFiles`. If the user uploads more than the allowed amount of files as set with `upload.setMaxFiles(intMaxFiles);` then any exceeding files are not uploaded, but no message is shown.

**Comment by IEnoobong** [comment]
Hello Friends. 

Any fix or workaround for this yet?

Happy to work on it too.

From forums - https://vaadin.com/forum/thread/17783847/upload-addfailedlistener-not-called-when-file-doesn-t-meet-constraints

**Comment by IEnoobong** [comment]
This is the solution/work around 

``` upload.getElement().addEventListener("file-reject", event -> onFileRejected(upload.getMaxFileSize(), event));``` But the event JsonObject is empty which is most likely due to a bug described below

The `vaadin-upload` web component fires a `file-reject` event, when the file doesn't meet specified constraints https://vaadin.com/components/vaadin-upload/html-examples/upload-limit-files-demos

But it's not being exposed in the component, however the functionality exists in `GeneratedVaadinUpload.addFileRejectListener` I tried to expose it but got a `ClassCastException` in `JsonCode.decodeAs`  from `flow-server` line 22

`java.lang.ClassCastException: Cannot cast elemental.json.impl.JreJsonString to elemental.json.JsonObject`

I'll try to look into fixing it later. Any guidance is appreciated.
