### ISSUE TITLE
Problem with @Id("...") binding

### ISSUE THREAD

**Issue by pbillen** [vaadin/vaadin-upload-flow#111]
Hi all,

I encountered the following problem.

In HTML:

```
<vaadin-upload id="upload" nodrop></vaadin-upload>
```

In Java:

```
public class MyView extends PolymerTemplate<Model> {
    private final MemoryBuffer buffer = new MemoryBuffer();
    @Id("upload")
    private final Upload       upload = new Upload(buffer);

    public MyView() {
        upload.addSucceededListener(event -> {
            System.out.println(event.getFileName());
            System.out.println(buffer.getInputStream());
        });
    }
}
```

Then I get when uploading a file:

```
java.lang.IllegalStateException: Upload cannot be performed without a receiver set
```

When using a `<slot>` in favor of `@Id("...")` as below, I don't have that problem:

In HTML:

```
<slot name="upload"></slot>
```

In Java:

```
public class MyView extends PolymerTemplate<Model> {
    private final MemoryBuffer buffer = new MemoryBuffer();
    private final Upload       upload = new Upload(buffer);

    public MyView() {
        upload.getElement().setAttribute("slot", "upload");
        upload.addSucceededListener(event -> {
            System.out.println(event.getFileName());
            System.out.println(buffer.getInputStream());
        });

        getElement().appendChild(upload.getElement());
    }
}
```

Please let me know if you need additional information.

Thanks!

**Comment by Legioth** [comment]
I haven't tried this out in practice, but I suspect the problem is that the `PolymerTemplate()` super constructor will inject a special component instance into the `upload` field. This will replace the instance that got a receiver through its constructor with a new instance without any receiver. To fix this, you should thus remove the field initialization and instead do `upload.setReceiver(buffer);` in the `MyView` constructor.

I remember there was some discussion about helping users avoid exactly this type of issue by rejecting cases when and `@Id` field already has a non-`null` value. I just cannot find that ticket, so it might have been an offline discussion.
